version: '3.1'
services:
  backend:
    container_name: vendetta-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
        - postgresDB:/var/lib/postgres
    networks:
      vendetta-network:

volumes:
  postgresDB:

networks:
  vendetta-network:
    driver: bridge
    external: true
